# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: random.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crandom.proto\"\x0f\n\rRandomRequest\"$\n\x0bRandomReply\x12\x15\n\rrandom_number\x18\x01 \x01(\x05\x32\x38\n\x06Random\x12.\n\x0c\x41skForRandom\x12\x0e.RandomRequest\x1a\x0c.RandomReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'random_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RANDOMREQUEST']._serialized_start=16
  _globals['_RANDOMREQUEST']._serialized_end=31
  _globals['_RANDOMREPLY']._serialized_start=33
  _globals['_RANDOMREPLY']._serialized_end=69
  _globals['_RANDOM']._serialized_start=71
  _globals['_RANDOM']._serialized_end=127
# @@protoc_insertion_point(module_scope)
