version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Benny
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql


  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "50051:50051"